words = [
    "Attendant :",
    "Azart :",
    "Bane :",
    "Blue :",
    "Bookcase :",
    "Boy :",
    "Breeze :",
    "Brigand :",
    "Buford :",
    "Bunza :",
    "Bunza:",
    "CROWD :",
    "Captain :",
    "Chef :",
    "Corona :",
    "Dd's Dau :",
    "Dd's Son :",
    "Dd's Wife :",
    "Dd'sMother:",
    "Dekka :",
    "Dew :",
    "Dodonpa :",
    "Dog :",
    "Donpa :",
    "Dora :",
    "Ember :",
    "Employee :",
    "F's Son :",
    "F's Wife :",
    "Faran :",
    "Feh :",
    "Feizhi :",
    "Fever :",
    "Fizz :",
    "Flash :",
    "Flint :",
    "Forge :",
    "G's Father:",
    "G's Mother:",
    "G's Sister:",
    "G'sBrother:",
    "G'sGrandma:",
    "G'sGrandpa:",
    "G. Healer :",
    "Galahad :",
    "Girl :",
    "Gladiator:",
    "Granite :",
    "Green :",
    "Ground :",
    "Guard :",
    "Guards :",
    "Guide :",
    "Guqard :",
    "Gust :",
    "Hail :",
    "Hama :",
    "Hammet :",
    "Head Chef :",
    "Head Chef:",
    "Healer :",
    "Hsu :",
    "Inn Chef :",
    "Innkeeper :",
    "Innkeeper:",
    "Iodem :",
    "J's Father:",
    "J's Mother:",
    "Jailed Man:",
    "Jenna'sGrF:",
    "Jenna'sGrM:",
    "Jill :",
    "Justin :",
    "Kaja :",
    "Kite :",
    "Kyle :",
    "Lady McCoy:",
    "Laurel :",
    "Layana :",
    "Lord McCoy:",
    "Luff :",
    "M'sGrandma:",
    "M'sGrandpa:",
    "Man :",
    "Masked Man:",
    "Mayor :",
    "Megan :",
    "Message :",
    "Mist :",
    "Morgan :",
    "Navampa :",
    "Navampa:",
    "Non-guide :",
    "Nyunpa :",
    "Oarsman :",
    "Old Man :",
    "Old Woman :",
    "Ouranos :",
    "Owner :",
    "Passenger:",
    "Plaque :",
    "Quartz :",
    "Red :",
    "Sap :",
    "Satrage :",
    "Scholar :",
    "Scorch :",
    "Sean :",
    "Shelf :",
    "Signpost :",
    "Sleet :",
    "Smog :",
    "Soldier :",
    "Spritz :",
    "Squall :",
    "Stage :",
    "Statue :",
    "Stone :",
    "Thief :",
    "Thief Head:",
    "Tonic :",
    "Torch :",
    "Tree :",
    "Tret :",
    "Vine :",
    "Violet :",
    "Waitress :",
    "Wardrobe :",
    "Warrior :",
    "Wise One :",
    "Woman :",
    "Worker :",
    "Writing :",
    "Yellow :",
    "Young Man :",
    "YoungWoman:",
    "Zephyr :",
    "colors:",
    "press A:"
]
# 使用 lambda 函数作为 key，按照单词长度从大到小进行排序
sorted_words = sorted(words, key=lambda x: len(x), reverse=True)

# 打印结果
for word in sorted_words:
    print(word)
